server {
    listen 80;
    root /var/www/html;
    index index.php index.html index.htm;

    # Jeśli plik lub folder nie istnieje, wyślij żądanie do index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # konfiguracja komunikacji Nginx -> PHP-FPM wewnątrz kontenera
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
    }
}